// packages/svelte/src/lib/UI/Message.svelte
<script lang="ts">
	import type { Appearance } from '$lib/types';
	import { css } from '@stitches/core';
	import { generateClassNames } from '@rtzr/auth-ui-shared';

	const messageDefaultStyles = css({
		fontFamily: '$bodyFontFamily',
		fontSize: '$baseBodySize',
		marginBottom: '$labelBottomMargin',
		display: 'block',
		textAlign: 'center',
		variants: {
			color: {
				default: {
					color: '$messageText'
				},
				danger: {
					color: '$messageTextDanger'
				}
			}
		}
	});

	type DivProps = svelte.JSX.HTMLAttributes<HTMLDivElement>;

	type $$Props = DivProps & {
		color?: 'default' | 'danger';
		appearance?: Appearance;
	};

	export let color: 'default' | 'danger' = 'default';
	export let appearance: Appearance = {};

	$: classNames = generateClassNames('message', messageDefaultStyles({ color }), appearance);
</script>

<span {...$$restProps} style={appearance?.style?.message} class={classNames.join(' ')}>
	<slot />
</span>

// packages/solid/src/components/UI/Message.tsx
import { css } from '@stitches/core'
import { Component, JSXElement, JSX } from 'solid-js'
import { generateClassNames } from '@rtzr/auth-ui-shared'
import { Appearance } from '../../types'

const messageDefaultStyles = css({
  fontFamily: '$bodyFontFamily',
  fontSize: '$baseBodySize',
  marginBottom: '$labelBottomMargin',
  display: 'block',
  textAlign: 'center',
  variants: {
    color: {
      default: {
        color: '$messageText',
      },
      danger: {
        color: '$messageTextDanger',
      },
    },
  },
})

interface MessageProps extends JSX.HTMLAttributes<HTMLSpanElement> {
  children: JSXElement
  color?: 'default' | 'danger'
  appearance?: Appearance
}

const Message: Component<MessageProps> = (props) => {
  const classNames = generateClassNames(
    'message',
    messageDefaultStyles({ color: props.color }),
    props.appearance
  )

  return (
    <span
      {...props}
      style={props.appearance?.style?.message}
      class={classNames.join(' ')}
    >
      {props.children}
    </span>
  )
}

export { Message }
