// packages/solid/src/components/Auth/interfaces/SocialAuth.tsx
import { Provider, SupabaseClient } from '@supabase/supabase-js'
import { createSignal, For, Show } from 'solid-js'
import { I18nVariables, SocialLayout, template } from '@rtzr/auth-ui-shared'
import { Appearance } from '../../../types'
import { Button, Container, Divider } from '../../UI'
import * as SocialIcons from '../Icons'

interface SocialAuthProps {
  supabaseClient: SupabaseClient
  socialLayout: SocialLayout | string
  providers?: Provider[]
  redirectTo: RedirectTo
  onlyThirdPartyProviders: boolean
  view: 'sign_in' | 'sign_up'
  i18n: I18nVariables
  appearance?: Appearance
}

type RedirectTo = undefined | string

function SocialAuth(props: SocialAuthProps) {
  const [loading, setLoading] = createSignal(false)
  const [error, setError] = createSignal('')

  const handleProviderSignIn = async (provider: Provider) => {
    setLoading(true)
    const { error } = await props.supabaseClient.auth.signInWithOAuth({
      provider,
      options: { redirectTo: props.redirectTo },
    })
    if (error) setError(error.message)
    setLoading(false)
  }

  function capitalize(word: string) {
    const lower = word.toLowerCase()
    return word.charAt(0).toUpperCase() + lower.slice(1)
  }

  return (
    <>
      {props.providers && props.providers.length > 0 && (
        <>
          <Container
            gap="large"
            direction="vertical"
            appearance={props.appearance}
          >
            <Container
              direction={props.socialLayout}
              gap={props.socialLayout === 'vertical' ? 'small' : 'medium'}
              appearance={props.appearance}
            >
              <For each={props.providers}>
                {(provider: Provider) => {
                  const AuthIcon = SocialIcons[provider]
                  return (
                    <Button
                      color="default"
                      icon={AuthIcon ? <AuthIcon /> : ''}
                      loading={loading()}
                      onClick={() => handleProviderSignIn(provider)}
                      appearance={props.appearance}
                    >
                      {props.socialLayout === 'vertical' &&
                        template(
                          props.i18n[props.view]
                            ?.social_provider_text as string,
                          {
                            provider: capitalize(provider),
                          }
                        )}
                    </Button>
                  )
                }}
              </For>
            </Container>
          </Container>
          <Show when={!props.onlyThirdPartyProviders}>
            <Divider appearance={props.appearance} />
          </Show>
        </>
      )}
    </>
  )
}

export { SocialAuth }

// packages/react/src/components/Auth/interfaces/SocialAuth.tsx
import { Provider, SupabaseClient } from '@supabase/supabase-js'
import { useState } from 'react'
import { I18nVariables, SocialLayout, template } from '@rtzr/auth-ui-shared'
import { Appearance } from '../../../types'
import { Button, Container, Divider } from './../../UI/index.js'
import * as SocialIcons from './../Icons.js'

interface SocialAuthProps {
  supabaseClient: SupabaseClient
  socialLayout?: SocialLayout
  providers?: Provider[]
  redirectTo?: RedirectTo
  onlyThirdPartyProviders?: boolean
  view?: 'sign_in' | 'sign_up'
  i18n?: I18nVariables
  appearance?: Appearance
}

type RedirectTo = undefined | string

function SocialAuth({
  supabaseClient,
  socialLayout = 'vertical',
  providers = ['github', 'google', 'azure'],
  redirectTo,
  onlyThirdPartyProviders = true,
  view = 'sign_in',
  i18n,
  appearance,
}: SocialAuthProps) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const verticalSocialLayout = socialLayout === 'vertical' ? true : false

  const handleProviderSignIn = async (provider: Provider) => {
    setLoading(true)
    const { error } = await supabaseClient.auth.signInWithOAuth({
      provider,
      options: { redirectTo },
    })
    if (error) setError(error.message)
    setLoading(false)
  }

  function capitalize(word: string) {
    const lower = word.toLowerCase()
    return word.charAt(0).toUpperCase() + lower.slice(1)
  }

  return (
    <>
      {providers && providers.length > 0 && (
        <>
          <Container gap="large" direction="vertical" appearance={appearance}>
            <Container
              direction={verticalSocialLayout ? 'vertical' : 'horizontal'}
              gap={verticalSocialLayout ? 'small' : 'medium'}
              appearance={appearance}
            >
              {providers.map((provider: Provider) => {
                const AuthIcon = SocialIcons[provider]
                return (
                  <Button
                    key={provider}
                    color="default"
                    icon={AuthIcon ? <AuthIcon /> : ''}
                    loading={loading}
                    onClick={() => handleProviderSignIn(provider)}
                    appearance={appearance}
                  >
                    {verticalSocialLayout &&
                      template(i18n?.[view]?.social_provider_text as string, {
                        provider: capitalize(provider),
                      })}
                  </Button>
                )
              })}
            </Container>
          </Container>
          {!onlyThirdPartyProviders && <Divider appearance={appearance} />}
        </>
      )}
    </>
  )
}

export { SocialAuth }
